### ISSUE TITLE
[Bounty:2] Enable Compact Block in Core Wallet

### ISSUE THREAD

**Issue by h4x3rotab** [BTCGPU/dev#1]
For simplification, Compact Block was disabled durning the hardfork last year. Compact Block is a part of the network protocol to improve the efficiency. It's also a pre-requirement for light Bitcoin client like Neutrino.

Requirements
1. Enable Compact Block in Core Wallet
2. Pass all the unit-tests

See also:
- [Compact Block](https://bitcoincore.org/en/2016/06/07/compact-blocks-faq/)
- [The commit disabling Compact Block](https://github.com/BTCGPU/BTCGPU/pull/15/commits/e2a965abd9a0b3bacef7d7e63cd58a7b5866cbbc)

What's the bounty? Check our [Public Bounty Program](https://github.com/BTCGPU/dev/blob/master/public-bounty.md).

**Comment by qasimsaleem1** [comment]
The developers can be found over here or you can post it here. People will help you a lot over here.
https://cryptojobslist.com/
https://crypto.jobs/
https://www.glassdoor.com/Job/crypto-jobs-SRCH_KO0,6.htm

**Comment by EricDualc** [comment]
@h4x3rotab Let me work on this issue.
But anyway, one question, is there any other issues what I can demonstrate my frontend GUI skill?

**Comment by h4x3rotab** [comment]
Hi @EricDualc, how is it going? We are working on merging Bitcoin Gold Core to v0.17.1 where the code of compact block is affected. If you are still on this, please kindly let us know so that we may avoid repeated work.

**Comment by h4x3rotab** [comment]
Fixed.
