### ISSUE TITLE
Create Testnet faucet

### ISSUE THREAD

**Issue by martin-key** [BTCGPU/dev#16]
A testnet faucet needs to be created for Bitcoin Gold. 
Features:
- connect to a node and have a protection so certain address is able to get TBTG only certain amount for 24 hours. 
- Captcha should be enabled. 
- Transaction history should be shown. 
- Address validation should be available. 
- Bitcoin Gold brand should be shown

**Comment by martin-key** [comment]
@h4x3rotab I would propose 25 BTG bounty for the one who create this and provide the source code

**Comment by h4x3rotab** [comment]
Done: https://test-faucet.bitcoinigold.org. Need to improve the stability
