### ISSUE TITLE
[Bounty: 1.5] Bitcore v8.9 enhancement

### ISSUE THREAD

**Issue by h4x3rotab** [BTCGPU/dev#19]
We already have a half-done Bitcore v8.9 (with Insight explorer) but it's testnet only and sometimes crashes due to unknown errors. This is for the enhancement on Bitcore.

Requirements

- Adapt BTG mainnet
- Add log output for debugging
- Pass all the tests

**Comment by h4x3rotab** [comment]
Fixed by:

- https://github.com/BTCGPU/bitcore/pull/3
- https://github.com/BTCGPU/bitcore/pull/4

**Comment by ssdbkey** [comment]
GQx3BNP2PtJpUdirc9AqDCDoTLac61vdDT

**Comment by h4x3rotab** [comment]
Done
