### ISSUE TITLE
[1500usd] TrustWallet integration

### ISSUE THREAD

**Issue by h4x3rotab** [BTCGPU/dev#20]
Trust Wallet is the official cryptocurrency wallet of Binance. It supports the top cryptocurrencies and ERC20 tokens. We would like to add BTG integration to TrustWallet.

Requirement:
- Integrate BTG to [Wallet Core](https://developer.trustwallet.com/wallet-core)
- Make a demo to sign transaction by [Wallet Connect](https://developer.trustwallet.com/wallet-connect/dapp)
- Tests and documents required to submit to TrustWallet repos.

**Comment by tolak** [comment]
GP3pAivzVc7XDGkETqHNZ4WwRy7F2UV6YJ

**Comment by h4x3rotab** [comment]
Sent 175 BTG @ $8.59
[9cfecdaae6699f18b675f5d6d699a04745c7148725e586ab73b64c31405c4389](https://explorer.bitcoingold.org/insight/tx/9cfecdaae6699f18b675f5d6d699a04745c7148725e586ab73b64c31405c4389)
