### ISSUE TITLE
Need 10 BTG Testnet

### ISSUE THREAD

**Issue by Droppix** [BTCGPU/dev#22]
Hi,

Due to the impossibility to find a good testnet faucet, could someone send me 10-50 BTG (Testnet) on the following address :
2N3X91NJ5VSZ1LD9AJDEGYxUbisUgD7cSxw

many thanks

**Comment by MentalNomad** [comment]
Cross-post, resolved here:

https://github.com/BTCGPU/BTCGPU/issues/409
