### ISSUE TITLE
[Bounty:15] OmniLayer for Bitcoin Gold

### ISSUE THREAD

**Issue by santos177** [BTCGPU/dev#7]
OmniLayer is the most popular software layer on top of Bitcoin, which uses block chain to enable features such as smart contracts, user currencies and decentralized peer-to-peer exchange. As an "agnostic layer"  omni has a few ports to other chains yet (litecoin, bitcoin cash) so is also possible integrate the layer on BTG. 

Requirements 

1. Full basic operations ported : create tokens, send issuance, crowdsale, metadex for tokens, Dex (btg exchange for layer tokens)  (done)
2. A demo for all functions  (done)
3. Basic documentation  (done)
4. Pass all the tests        (work in progress)
5. Rebase to the original OmniCore branch (work in progress)

Current Work:
https://github.com/santos177/OmniG

See also:
https://www.omnilayer.org/

**Comment by h4x3rotab** [comment]
Let me add a new requirement: Rebase to the original OmniCore branch to make it easier to review

**Comment by h4x3rotab** [comment]
OmniLayer on BTG is certainly an interesting idea! It will enable BTG to support user issues assets with onchine exchange. I love the idea and the bounty you propose looks good. Please make sure the code is reviewable.

**Comment by h4x3rotab** [comment]
@santos177 has already finished the bounty. Will keep this issue until all the payments are finished.
